= Distributed Transactions from the C++ SDK
:navtitle: ACID Transactions
:page-topic-type: howto
:page-aliases: acid-transactions
:page-status: Developer Preview


[abstract]
A practical guide to using Couchbase’s distributed ACID transactions, via the C++ API.


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=intro]

The {cpp} Transactions API is built upon the Couchbase C SDK, _libcouchbase_ (LCB), which is automatically installed by the transactions library.
Applications built using C SDK and C Transactions can run in parallel without interfering with each other.

Below we show you how to create Transactions, step-by-step.
You may also want to start with our https://github.com/couchbaselabs/couchbase-transactions-java-examples[transactions examples repository],
which features useful downloadable examples of using Distributed Transactions.

API docs are available https://docs.couchbase.com/sdk-api/couchbase-transactions-cxx-1.0.0-beta.1/index.html[online].


== Requirements

* Couchbase Server 6.6 or above.
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured.
Simply add the transactions library into your project.
The latest version, as of October 2020, is 1.0.0.beta.1.

The following steps show how to build and run our example project on CentOS 8:

[source,console]
----
$ sudo yum groupinstall "Development Tools"
$ sudo yum install boost-devel
----

[source,console]
----
$ wget https://sdk-snapshots.couchbase.com/clients/transactions-cxx/couchbase-transactions-1.0.0-0.beta.1.63.el8.x86_64.tar
$ tar xf couchbase-transactions-1.0.0-0.beta.1.63.el8.x86_64.tar
$ sudo yum install couchbase-transactions*.rpm
----

[source,console]
----
$ git clone git://github.com/couchbaselabs/couchbase-transactions-cxx-examples.git
$ cd couchbase-transactions-cxx-examples/game/
$ mkdir build && cd build
$ cmake ../
$ make
----

[source,console]
----
$ ./game_server
----

== Initializing Transactions

The starting point is the `transactions` object.
It is very important that the application ensures that only one of these is created, as it performs automated background processes that should not be duplicated.

[source,c++]
----
include::example$transactions-example.cxx[tag=init,indent=0]
----


== Configuration

Transactions can optionally be configured at the point of creating the `transactions` object:

[source,c++]
----
include::example$transactions-example.cxx[tag=config,indent=0]
----

include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=config]


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,c++]
----
include::example$transactions-example.cxx[tag=create,indent=0]
----


== Examples

A code example is worth a thousand words, so here is a quick summary of the main transaction operations.

[source,c++]
----
include::example$transactions-example.cxx[tag=examples,indent=0]
----


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=mechanics]


== Mutating Documents

=== Replacing

Replacing a document requires a `ctx.get()` call first.
This is necessary to ensure that the document is not involved in another transaction.
(If it is, then the transaction will handle this, generally by rolling back what has been done so far, and retrying the lambda.)

[source,c++]
----
include::example$transactions-example.cxx[tag=replace,indent=0]
----

=== Removing

As with replaces, removing a document requires a `ctx.get()` call first.

[source,c++]
----
include::example$transactions-example.cxx[tag=remove,indent=0]
----

=== Inserting

[source,c++]
----
include::example$transactions-example.cxx[tag=insert,indent=0]
----


== Getting Documents

There are two ways to get a document, `get` and `getOptional`:

[source,c++]
----
include::example$transactions-example.cxx[tag=get,indent=0]
----

`get` will cause the transaction to fail with `transaction_failed` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check the `optional` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,c++]
----
include::example$transactions-example.cxx[tag=getReadOwnWrites,indent=0]
----

== Committing

Committing is automatic: if there is no explicit call to `ctx.commit()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.

As soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed - even if the application crashes.


== Threads

The `cluster`, `bucket`, `collection`, and  `transactions` objects all are safe to use across multiple threads.  When creating
the `cluster`, you can specify the maximum number of `libcouchbase` instances the `cluster` and `bucket` can use.  Transactions
currently only using KV operations from the `bucket`.  Specifying `max_bucket_instances` in the `cluster_options` when creating
the `cluster` is sufficient.  This will be the maximum number of concurrent transaction operations which can be made:

[source,c++]
----
include::example$transactions-example.cxx[tag=max_bucket_instances,indent=0]
----

The example below allows for up to 10 instances to be created, then has 10 threads `get` and `replace` the content in a document:

[source,c++]
----
include::example$transactions-example.cxx[tag=threads,indent=0]
----



// == A Full Transaction Example
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=example]

A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-java-examples[GitHub transactions examples page].

[source,c++]
----
include::example$transactions-example.cxx[tag=full,indent=0]
----


== Concurrency with Non-Transactional Writes

This release of transactions for Couchbase requires a degree of co-operation from the application.
Specifically, the application should ensure that non-transactional writes (such as key-value writes or N1QL UPDATES) are never done concurrently with transactional writes, on the same document.

This requirement is to ensure that the strong Key-Value performance of Couchbase was not compromised.
A key philosophy of our transactions is that you 'pay only for what you use'.

If two such writes *do* conflict then the transactional write will 'win', overwriting the non-transactional write.

Note this only applies to _writes_.
Any non-transactional _reads_ concurrent with transactions are fine, and are at a Read Committed level.


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

If the transaction is not retried then it will throw a `transaction_failed` exception, and its `cause` method can be used for more details on the failure.
The application can use this to signal why it triggered a rollback.

The transaction can also be explicitly rolled back:

[source,c++]
----
include::example$transactions-example.cxx[tag=rollback,indent=0]
----

In this case, if `ctx.rollback()` is reached, then the transaction will be regarded as successfully rolled back and no TransactionFailed will be thrown.

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the library will not try to automatically commit it at the end of the code block.


//  Error Handling
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=error]



//  txnfailed
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

[source,c++]
----
include::example$transactions-example.cxx[tag=config-expiration,indent=0]
----

include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed1]


== Logging

To aid troubleshooting, the transactions library logs information to `stdout`.  The default logging level is `INFO`, but can
be changed to produce more or less detailed output.  For instance, to see very detailed logging:

[source,c++]
----
include::example$transactions-example.cxx[tag=config_trace,indent=0]
----

== Further Reading

* There’s plenty of explanation about how Transactions work in Couchbase in our xref:6.6@server:learn:data/transactions.adoc[Transactions documentation].
* You can find further code examples on our https://github.com/couchbaselabs/couchbase-transactions-cxx-examples[transactions examples repository].
